version: "3.3"
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./tunnel.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  starlink_exporter:
    image: "ghcr.io/danopstech/starlink_exporter:latest"
    restart: always
    ports:
      - "9010:9817"

  speedtest_exporter:
    image: "ghcr.io/danopstech/speedtest_exporter:latest"
    restart: always
    ports:
      - "9011:9090"

  renogybt_exporter:
    image: "ghcr.io/macrofig/renogy-solar-exporter:latest"
    restart: always
    volumes:
      - /run/dbus:/run/dbus:ro
    ports:
      - "9012:9030"

  prometheus:
    image: "ghcr.io/danopstech/prometheus:latest"
    restart: always
    user: "root"
    ports:
      - "9020:9090"
    volumes:
      - type: bind
        source: ./config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./data/prometheus
        target: /prometheus

  grafana:
    image: "ghcr.io/danopstech/grafana:latest"
    restart: always
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_CONSOLE_LEVEL=warn
    volumes:
      - type: bind
        source: ./data/grafana
        target: /var/lib/grafana
      - type: bind
        source: ./config/grafana
        target: /etc/grafana/provisioning/
secrets:
  tunnel_key:
    file: tunnel_key.txt