{
 "title": "Power System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "load_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "charging_amp_hours_today - discharging_amp_hours_today",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "battery_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pv_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "battery_voltage", "legendFormat": "Battery Voltage" },
    { "expr": "avg(pv_voltage)", "legendFormat": "Solar Voltage" }
   ]
  },
  {
   "title": "Battery Health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "battery_voltage", "legendFormat": "BatteryVoltage" }
   ]
  },
  {
   "title": "Charge to Battery",
   "type": "timeseries",
   "description": "Shows how much current is being pulled from solar versus batteries. ",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(battery_current)", "legendFormat": "Amps" },
    { "expr": "avg(battery_voltage)", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    { "expr": "pv_current", "legendFormat": "Amps" },
    { "expr": "pv_voltage", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "pv_power", "legendFormat": "Solar" },
    { "expr": "load_power", "legendFormat": "Load" }
   ]
  }
 ]
}